apiVersion: v1
kind: Pod 
metadata:
  name: example-pod
  namespace: prodns
spec:
  containers:
    - name: test-cont
      image: muralisocial123/node-app-example
      ports:
        - containerPort: 3000 
    - name: web-app
      image: nginx
      ports:
        - containerPort: 80