apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    name: myapp
spec:
  containers:
  - name: sample
    image: nginx
    ports:
      - containerPort: 80
    env:
      - name: Password 
        valueFrom:
          secretKeyRef:
            key: password 
            name: mysecret