apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::124355663661:role/eksctl-clahan-murali-cluster-nodeg-NodeInstanceRole-yO86EeARN81c
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::124355663661:user/roboshop-admin
      username: roboshop-admin
    - userarn: arn:aws:iam::124355663661:user/Murali
      username: Murali   
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-08T15:59:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1199"
  uid: 8c8209e7-f5b1-4462-9abd-71b22a41dd02  