apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: murali-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: murali-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: murali-admin-role
subjects:
  - kind: User
    name: Murali
    apiGroup: rbac.authorization.k8s.io
